version: '3.8'

services:
  portfolio:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: portfolio-website
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge