name: Update README Stats

on:
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch: {}

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Update README
        env:
          GH_STATS_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: node scripts/update-readme.mjs

      - name: Commit and push if changed
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md portfolio/README.md || true
            git commit -m "chore: update README stats"
            git push
          else
            echo "No changes to commit"
          fi
name: Update README GitHub Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  push:
    paths:
      - "README.md"
      - "portfolio/README.md"
      - "scripts/update-readme.mjs"
      - ".github/workflows/update-readme.yml"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Update READMEs
        run: node scripts/update-readme.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(readme): auto-update GitHub stats and links"
          file_pattern: |
            README.md
            portfolio/README.md
